---
title: "Lab Name"
author: "Author Name"
date: "`r Sys.Date()`"
output: openintro::lab_report
---

```{r load-packages, message=FALSE}
library(tidyverse)
library(openintro)
library(sf)
library(ggplot2)
```

### Exercise 1

Insert any text here.

```{r code-chunk-label}



getwd()


mapping_inequality <- st_read("mappinginequality.gpkg")

head(mapping_inequality)

View(mapping_inequality)

```

Washington Redlining ????? 

```{r}


WA_data <- mapping_inequality[mapping_inequality$state == "WA", ]


ggplot() +
  geom_sf(data = WA_data, aes(fill = category)) +
  theme_minimal() +
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()) 


```






### Exercise 2


```{r}




seattle_data <- mapping_inequality[mapping_inequality$city == "Seattle", ]


#### Color based on Grade

ggplot() +
  geom_sf(data = seattle_data, aes(fill = grade)) +
  scale_fill_manual(values = c("A" = "blue", "B" = "green", "C" = "yellow", "D" = "orange", "E" = "red", "Unknown" = "gray")) + 
  theme_minimal()



#### Color based on Category
ggplot() +
  geom_sf(data = seattle_data, aes(fill = category)) +
  theme_minimal()



ggplot() +
  geom_sf(data = seattle_data, aes(fill = category)) +
  theme_minimal() +
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
  labs(title = "Redlining Map of Seattle")



```





Making Seattle Map Prettier

A. Best
B. Still Desirable
C. Definitely Declining 
D. Hazardous
E. Business
E. Industrial



```{r}


#### Color based on Grade

ggplot() +
  geom_sf(data = seattle_data, aes(fill = grade)) +
  scale_fill_manual(values = c("A" = "green", "B" = "blue", "C" = "yellow", "D" = "red", "Unknown" = "light gray")) + 
  theme_minimal() +
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
  labs(title = "Redlining Map of Seattle")




ggplot() +
  geom_sf(data = seattle_data, aes(fill = grade)) +
  scale_fill_manual(values = c("A" = "green", "B" = "blue", "C" = "yellow", "D" = "red", "Unknown" = "light gray"),
                    labels = c("A. Best", "B. Still Desirable", "C. Definitely Declining ", "D. Hazardous", "E. Industrial/Bussiness")) + 
  theme_minimal() +
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
  labs(title = "Redlining Map of Seattle")


ggplot() +
  geom_sf(data = seattle_data, aes(fill = grade)) +
  scale_fill_manual(values = c("A" = "mediumseagreen", "B" = "dodgerblue3", "C" = "khaki1", "D" = "indianred", "Unknown" = "gray48"),
                    labels = c("A. Best", "B. Still Desirable", "C. Definitely Declining", "D. Hazardous", "E. Industrial/Business"),
                    name = "Grade of Security") + 
  theme_minimal() +
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
  labs(title = "Seattle Redlining Map")



Seattle_Redline_Map1 <- ggplot(width = 20, height = 10) +
  geom_sf(data = seattle_data, aes(fill = grade)) +
  scale_fill_manual(values = c("A" = "mediumseagreen", "B" = "dodgerblue3", "C" = "khaki1", "D" = "indianred", "Unknown" = "gray48"),
                    labels = c("A. Best", "B. Still Desirable", "C. Definitely Declining", "D. Hazardous", "E. Industrial/Business"),
                    name = "Grade of Security") + 
  theme_minimal() +
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
  labs(title = "Redlining Map of Seattle")


Seattle_Redline_Map1

```

...

