---
title: "Evaluation of the ERAP Index and Modern Effects of Redlining"
author: "Savannah Meyer, Benyamin Yeimo, Emily Blue, Mark Clemmer"
date: "2024-06-03"
output: html_document
---
```{r include=FALSE}
library(httr)
library(jsonlite)
library(sf)
library(tidyverse)
library(car)
library(plotly)
library(leaps)

my_map_theme <- function(){
  theme(panel.background=element_blank(),
        axis.text=element_blank(),
        axis.ticks=element_blank(),
        axis.title=element_blank())
}

```

## Abstract: 

## Introduction:

## Methods:

## Results:

## Discussion:
###ERAP indicators Results Discussion:

###Limitations:

### Eviction vs. ERAP Index Results:


$$
\begin{aligned}
\widehat{\text{eviction_rate}} = & \ -1.194 + 0.006423 \cdot \text{income_subindex_value} - 0.005748 \cdot \text{hh_chars_subindex_value} \\
  & \ + 5.138 \cdot \text{percent_renter_occ_units} + 0.06893 \cdot \text{poverty.rate} + 0.000697 \cdot \text{median.gross.rent} \\ 
  & \ + 0.00001356 \cdot \text{median.household.income} - 0.000004625 \cdot \text{median.property.value}
\end{aligned}
$$
```{r echo=FALSE, message=FALSE, warning=FALSE}
wa_eviction_erap_tracts <- st_read("../data/wa_eviction_erap_tracts.geojson", quiet=TRUE)
wa_eviction_erap_tracts$text <- paste("<b>Tract", wa_eviction_erap_tracts$census_tract, "of", wa_eviction_erap_tracts$county_name,
              "<b><br>ERAP Index:", wa_eviction_erap_tracts$index_value,
              "<br>Eviction Rate:",round( wa_eviction_erap_tracts$eviction_rate,3),
              "<br>Population:", wa_eviction_erap_tracts$population,
              "<br>Poverty Rate:", wa_eviction_erap_tracts$poverty.rate)


wa_map <- ggplot(wa_eviction_erap_tracts) +
  geom_sf(aes(fill = index_value, text = text)) +
  scale_fill_continuous("ERAP Index Value",
                        low="yellow",
                        high="red") +
  my_map_theme() +
  ggtitle("Evictions and ERAP Index by census tract in Washington")


ggplotly(wa_map, tooltip = "text") |>
  style(hoveron = "fills+points")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Now Illinois
il_eviction_erap_tracts <- st_read("../data/il_eviction_erap_tracts.geojson", quiet=TRUE)
il_eviction_erap_tracts$text <- paste("<b>Tract", il_eviction_erap_tracts$census_tract, "of", il_eviction_erap_tracts$county_name,
              "<b><br>ERAP Index:", il_eviction_erap_tracts$index_value,
              "<br>Eviction Rate:",round( il_eviction_erap_tracts$eviction_rate,3),
              "<br>Population:", il_eviction_erap_tracts$population,
              "<br>Poverty Rate:", il_eviction_erap_tracts$poverty.rate)

il_map <- ggplot(il_eviction_erap_tracts) +
  geom_sf(aes(fill = index_value, text = text)) +
  scale_fill_continuous("ERAP Index Value",
                        low="yellow",
                        high="red") +
  my_map_theme() +
  ggtitle("Evictions and ERAP Index by census tract in Illinois")


ggplotly(il_map, tooltip = "text") |>
  style(hoveron = "fills+points")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Now Ohio
oh_eviction_erap_tracts <- st_read("../data/oh_eviction_erap_tracts.geojson", quiet=TRUE)
oh_eviction_erap_tracts$text <- paste("<b>Tract", oh_eviction_erap_tracts$census_tract, "of", oh_eviction_erap_tracts$county_name,
              "<b><br>ERAP Index:", oh_eviction_erap_tracts$index_value,
              "<br>Eviction Rate:",round( oh_eviction_erap_tracts$eviction_rate,3),
              "<br>Population:", oh_eviction_erap_tracts$population,
              "<br>Poverty Rate:", oh_eviction_erap_tracts$poverty.rate)

oh_map <- ggplot(oh_eviction_erap_tracts) +
  geom_sf(aes(fill = index_value, text = text)) +
  scale_fill_continuous("ERAP Index Value",
                        low="yellow",
                        high="red") +
  my_map_theme() +
  ggtitle("Evictions and ERAP Index by census tract in Ohio")


ggplotly(oh_map, tooltip = "text") |>
  style(hoveron = "fills+points")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Map Pennsylvania
pa_eviction_erap_tracts <- st_read("../data/pa_eviction_erap_tracts.geojson", quiet=TRUE)
pa_eviction_erap_tracts$text <- paste("<b>Tract", pa_eviction_erap_tracts$census_tract, "of", pa_eviction_erap_tracts$county_name,
              "<b><br>ERAP Index:", pa_eviction_erap_tracts$index_value,
              "<br>Eviction Rate:",round( pa_eviction_erap_tracts$eviction_rate,3),
              "<br>Population:", pa_eviction_erap_tracts$population,
              "<br>Poverty Rate:", pa_eviction_erap_tracts$poverty.rate)

pa_map <- ggplot(pa_eviction_erap_tracts) +
  geom_sf(aes(fill = index_value, text = text)) +
  scale_fill_continuous("ERAP Index Value",
                        low="yellow",
                        high="red") +
  my_map_theme() +
  ggtitle("Evictions and ERAP Index by census tract in Pennsylvania")


ggplotly(pa_map, tooltip = "text") |>
  style(hoveron = "fills+points")
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
seattle_erap_red_evic <- st_read("../data/seattle_erap_red_evic.geojson")
seattle_erap_red_evic$text <- paste("<b>Tract", seattle_erap_red_evic$census_tract,
              "<b><br>ERAP Index:", seattle_erap_red_evic$index_value,
              "<br>Eviction Rate:",round(seattle_erap_red_evic$eviction_rate,3),
              "<br>Grade", seattle_erap_red_evic$grade, ":", seattle_erap_red_evic$cat,
              "<br>Population:", seattle_erap_red_evic$population,
              "<br>Poverty Rate:", seattle_erap_red_evic$poverty.rate)

seattle_map <- ggplot(seattle_erap_red_evic) +
  geom_sf(aes(fill = eviction_rate, text = text)) +
  scale_fill_continuous("Eviction Rate",
                        low="yellow",
                        high="red") +
  my_map_theme() +
  ggtitle("Evictions by census tract in Seattle")


ggplotly(seattle_map, tooltip = "text") |>
  style(hoveron = "fills+points")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
chicago_erap_red_evic <- st_read("../data/chicago_erap_red_evic.geojson")
chicago_erap_red_evic$text <- paste("<b>Tract", chicago_erap_red_evic$census_tract,
              "<b><br>ERAP Index:", chicago_erap_red_evic$index_value,
              "<br>Eviction Rate:",round( chicago_erap_red_evic$eviction_rate,3),
              "<br>Grade", chicago_erap_red_evic$grade, ":", chicago_erap_red_evic$cat,
              "<br>Population:", chicago_erap_red_evic$population,
              "<br>Poverty Rate:", chicago_erap_red_evic$poverty.rate)

chicago_map <- ggplot(chicago_erap_red_evic) +
  geom_sf(aes(fill = eviction_rate, text = text)) +
  scale_fill_continuous("Eviction Rate",
                        low="yellow",
                        high="red") +
  my_map_theme() +
  ggtitle("Evictions by census tract in Chicago")


ggplotly(chicago_map, tooltip = "text") |>
  style(hoveron = "fills+points")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
pittsburgh_erap_red_evic <- st_read("../data/pittsburgh_erap_red_evic.geojson")
pittsburgh_erap_red_evic$text <- paste("<b>Tract", pittsburgh_erap_red_evic$census_tract,
              "<b><br>ERAP Index:", pittsburgh_erap_red_evic$index_value,
              "<br>Eviction Rate:",round( pittsburgh_erap_red_evic$eviction_rate,3),
              "<br>Grade", pittsburgh_erap_red_evic$grade, ":", pittsburgh_erap_red_evic$cat,
              "<br>Population:", pittsburgh_erap_red_evic$population,
              "<br>Poverty Rate:", pittsburgh_erap_red_evic$poverty.rate)

pittsburgh_map <- ggplot(pittsburgh_erap_red_evic) +
  geom_sf(aes(fill = eviction_rate, text = text)) +
  scale_fill_continuous("Eviction Rate",
                        low="yellow",
                        high="red") +
  my_map_theme() +
  ggtitle("Evictions by census tract in Pittsburgh")


ggplotly(pittsburgh_map, tooltip = "text") |>
  style(hoveron = "fills+points")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
cleveland_erap_red_evic <- st_read("../data/cleveland_erap_red_evic.geojson")
cleveland_erap_red_evic$text <- paste("<b>Tract", cleveland_erap_red_evic$census_tract,
              "<b><br>ERAP Index:", cleveland_erap_red_evic$index_value,
              "<br>Eviction Rate:",round( cleveland_erap_red_evic$eviction_rate,3),
              "<br>Grade", cleveland_erap_red_evic$grade, ":", cleveland_erap_red_evic$cat,
              "<br>Population:", cleveland_erap_red_evic$population,
              "<br>Poverty Rate:", cleveland_erap_red_evic$poverty.rate)

cleveland_map <- ggplot(cleveland_erap_red_evic) +
  geom_sf(aes(fill = eviction_rate, text = text)) +
  scale_fill_continuous("Eviction Rate",
                        low="yellow",
                        high="red") +
  my_map_theme() +
  ggtitle("Evictions by census tract in Cleveland")


ggplotly(cleveland_map, tooltip = "text") |>
  style(hoveron = "fills+points")

```

```{r echo=FALSE, message=FALSE, warning=FALSE}
plotly1 <- ggplotly(il_map, tooltip = "text") |>
  style(hoveron = "fills+points")
plotly2 <- ggplotly(pa_map, tooltip = "text") |>
  style(hoveron = "fills+points")

#subplot(plotly1, plotly2, nrows = 1, margin = 0.05) |> 
#  layout(title = "Map A Vs. Map B", titlefont = list(size = 30, face = "bold"))
```




### Limitations:

### Redlining Results:

```{r echo=FALSE, message=FALSE, warning=FALSE}

Cleveland__erap_redlining_dataset <- st_read("../data/Cleveland_erap_redlining.geojson", quiet=TRUE)

Seattle_erap_redlining_dataset <- st_read("../data/Seattle_erap_redlining.geojson", quiet=TRUE)

Pittsburgh_erap_redlining_dataset <- st_read("../data/Pittsburgh_erap_redlining.geojson", quiet=TRUE)

Chicago_erap_redlining_dataset <- st_read("../data/Chicago_erap_redlining.geojson", quiet=TRUE)

```


```{r echo=FALSE, message=FALSE, warning=FALSE}
sea_poc_boxplot <- ggplot(data = Seattle_erap_redlining_dataset) +
  aes(x = grade, y = percent_minority, fill = grade) +  
  geom_boxplot(alpha = 0.5) +
  ggtitle(expression(atop(bold("Seattle"), atop(italic("Current Minority Percentage by HOC Redlining Grade"), "")))) + 
  labs(x = "", y = "Current POC %") +
  scale_x_discrete(labels = c(
    "A" = expression(atop(bold("A."), "Best")),
    "B" = expression(atop(bold("B."), "Still Desirable")),
    "C" = expression(atop(bold("C."), "Definitely Declining")),
    "D" = expression(atop(bold("D."), "Hazardous")),
    "E" = expression(atop(bold("E."), "Industrial/Business"))
  )) +
  scale_fill_manual(values = c("A" = "mediumseagreen", "B" = "dodgerblue3", "C" = "khaki1", "D" = "indianred", "E" = "gray48")) +
  theme(panel.grid.major.y = element_blank(),  
        panel.grid.major.x = element_line(color = "gray", linetype = "dotted"),
        axis.text.x = element_text(size = 8))

sea_poc_boxplot
```


```{r echo=FALSE, message=FALSE, warning=FALSE}

chicago_poc_boxplot <- ggplot(data = Chicago_erap_redlining_dataset) +
  aes(x = grade, y = percent_minority, fill = grade) +  
  geom_boxplot(alpha = 0.5) +
  ggtitle(expression(atop(bold("Chicago"), atop(italic("Current Minority Percentage by HOC Redlining Grade"), "")))) + 
  labs(x = "", y = "Current POC %") +
  scale_x_discrete(labels = c(
    "A" = expression(atop(bold("A."), "Best")),
    "B" = expression(atop(bold("B."), "Still Desirable")),
    "C" = expression(atop(bold("C."), "Definitely Declining")),
    "D" = expression(atop(bold("D."), "Hazardous")),
    "E" = expression(atop(bold("E."), "Industrial/Business"))
  )) +
  scale_fill_manual(values = c("A" = "mediumseagreen", "B" = "dodgerblue3", "C" = "khaki1", "D" = "indianred", "E" = "gray48")) +
  theme(panel.grid.major.y = element_blank(),  
        panel.grid.major.x = element_line(color = "gray", linetype = "dotted"),
        axis.text.x = element_text(size = 8))

chicago_poc_boxplot

```


```{r echo=FALSE, message=FALSE, warning=FALSE}

pitts_poc_boxplot <- ggplot(data = Pittsburgh_erap_redlining_dataset) +
  aes(x = grade, y = percent_minority, fill = grade) +  
  geom_boxplot(alpha = 0.5) +
  ggtitle(expression(atop(bold("Pittsburgh"), atop(italic("Current Minority Percentage by HOC Redlining Grade"), "")))) + 
  labs(x = "", y = "Current POC %") +
  scale_x_discrete(labels = c(
    "A" = expression(atop(bold("A."), "Best")),
    "B" = expression(atop(bold("B."), "Still Desirable")),
    "C" = expression(atop(bold("C."), "Definitely Declining")),
    "D" = expression(atop(bold("D."), "Hazardous")),
    "E" = expression(atop(bold("E."), "Industrial/Business"))
  )) +
  scale_fill_manual(values = c("A" = "mediumseagreen", "B" = "dodgerblue3", "C" = "khaki1", "D" = "indianred", "E" = "gray48")) +
  theme(panel.grid.major.y = element_blank(),  
        panel.grid.major.x = element_line(color = "gray", linetype = "dotted"),
        axis.text.x = element_text(size = 8))

pitts_poc_boxplot

```

```{r echo=FALSE, message=FALSE, warning=FALSE}


clev_poc_boxplot <- ggplot(data = Cleveland__erap_redlining_dataset) +
  aes(x = grade, y = percent_minority, fill = grade) +  
  geom_boxplot(alpha = 0.5) +
  ggtitle(expression(atop(bold("Cleveland"), atop(italic("Current Minority Percentage by HOC Redlining Grade"), "")))) + 
  labs(x = "", y = "Current POC %") +
  scale_x_discrete(labels = c(
    "A" = expression(atop(bold("A."), "Best")),
    "B" = expression(atop(bold("B."), "Still Desirable")),
    "C" = expression(atop(bold("C."), "Definitely Declining")),
    "D" = expression(atop(bold("D."), "Hazardous")),
    "E" = expression(atop(bold("E."), "Industrial/Business"))
  )) +
  scale_fill_manual(values = c("A" = "mediumseagreen", "B" = "dodgerblue3", "C" = "khaki1", "D" = "indianred", "E" = "gray48")) +
  theme(panel.grid.major.y = element_blank(),  
        panel.grid.major.x = element_line(color = "gray", linetype = "dotted"),
        axis.text.x = element_text(size = 8))


clev_poc_boxplot

```


```{r echo=FALSE, message=FALSE, warning=FALSE}

Sea_map2 <-ggplot(width = 30, height = 15) +
  geom_sf(data = Seattle_erap_redlining_dataset, aes(fill = grade, 
                                      text = paste("Grade", grade, ":", cat, "<br>",
                                                   "Percent Minority:", percent_minority_pct, "%", "<br>", "<br>",
                                                   ifelse(grade != "E", paste("Label:", label, "<br>"), ""),
                                                   "ERAP Value:", index_value, "<br>",
                                                   "Median Monthly Cost: $", median_monthly_housing_cost, "<br>",
                                                   "Cost Burdened Renters:", percent_cost_burdened_renters_pct, "%"))) +
  scale_fill_manual(values = c("A" = "mediumseagreen", "B" = "dodgerblue3", "C" = "khaki1", "D" = "indianred", "E" = "gray48"),
                    labels = c("A. Best", "B. Still Desirable", "C. Definitely Declining", "D. Hazardous", "E. Industrial/Business"),
                    name = "Grade of Security") + 
  theme_minimal() +
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(family = "Times New Roman", size = 15)) +  
  labs(title = "<b>Redlining Map: <span style='font-size: larger;'>Seattle</span></b>")


Sea_map2_plotly <- ggplotly(Sea_map2, tooltip = "text")
Sea_map2_plotly 

```


```{r echo=FALSE, message=FALSE, warning=FALSE}


Chicago_red_map1 <- ggplot(width = 30, height = 15) +
  geom_sf(data = Chicago_erap_redlining_dataset, aes(fill = grade, 
                                      text =paste("Grade", grade, ":", cat, "<br>",
                                                   "Percent Minority:", percent_minority_pct, "%", "<br>", "<br>",
                                                   ifelse(grade != "E", paste("Label:", label, "<br>"), ""),
                                                   "ERAP Value:", index_value, "<br>",
                                                   "Median Monthly Cost: $", median_monthly_housing_cost, "<br>",
                                                   "Cost Burdened Renters:", percent_cost_burdened_renters_pct, "%"))) +
  scale_fill_manual(values = c("A" = "mediumseagreen", "B" = "dodgerblue3", "C" = "khaki1", "D" = "indianred", "E" = "gray48"),
                    labels = c("A. Best", "B. Still Desirable", "C. Definitely Declining", "D. Hazardous", "E. Industrial/Business"),
                    name = "Grade of Security") + 
  theme_minimal() +
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(family = "Times New Roman", size = 15)) +  
  labs(title = "<b>Redlining Map: <span style='font-size: larger;'>Chicago</span></b>")


Chicago_map_plotly <- ggplotly(Chicago_red_map1, tooltip = "text")


Chicago_map_plotly


```

```{r echo=FALSE, message=FALSE, warning=FALSE}

Pitts_map1 <- ggplot(width = 30, height = 15) +
  geom_sf(data = Pittsburgh_erap_redlining_dataset, aes(fill = grade, 
                                      text = paste("Grade", grade, ":", cat, "<br>",
                                                   "Percent Minority:", percent_minority_pct, "%", "<br>", "<br>",
                                                   ifelse(grade != "E", paste("Label:", label, "<br>"), ""),
                                                   "ERAP Value:", index_value, "<br>",
                                                   "Median Monthly Cost: $", median_monthly_housing_cost, "<br>",
                                                   "Cost Burdened Renters:", percent_cost_burdened_renters_pct, "%"))) +
  scale_fill_manual(values = c("A" = "mediumseagreen", "B" = "dodgerblue3", "C" = "khaki1", "D" = "indianred", "E" = "gray48"),
                    labels = c("A. Best", "B. Still Desirable", "C. Definitely Declining", "D. Hazardous", "E. Industrial/Business"),
                    name = "Grade of Security") + 
  theme_minimal() +
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(family = "Times New Roman", size = 15)) +  
  labs(title = "<b>Redlining Map: <span style='font-size: larger;'>Pittsburgh</span></b>")



Pitts_map1_plotly <- ggplotly(Pitts_map1 , tooltip = "text")

Pitts_map1_plotly

```

```{r echo=FALSE, message=FALSE, warning=FALSE}

Clev_2red_map <- ggplot(width = 30, height = 15) +
  geom_sf(data = Cleveland__erap_redlining_dataset, aes(fill = grade, 
                                      text =paste("Grade", grade, ":", cat, "<br>",
                                                   "Percent Minority:", percent_minority_pct, "%", "<br>", "<br>",
                                                   ifelse(grade != "E", paste("Label:", label, "<br>"), ""),
                                                   "ERAP Value:", index_value, "<br>",
                                                   "Median Monthly Cost: $", median_monthly_housing_cost, "<br>",
                                                   "Cost Burdened Renters:", percent_cost_burdened_renters_pct, "%"))) +
  scale_fill_manual(values = c("A" = "mediumseagreen", "B" = "dodgerblue3", "C" = "khaki1", "D" = "indianred", "E" = "gray48"),
                    labels = c("A. Best", "B. Still Desirable", "C. Definitely Declining", "D. Hazardous", "E. Industrial/Business"),
                    name = "Grade of Security") + 
  theme_minimal() +
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(family = "Times New Roman", size = 15)) +  
  labs(title = "<b>Redlining Map: <span style='font-size: larger;'>Cleveland</span></b>")



Clev_map_plotly <- ggplotly(Clev_2red_map, tooltip = "text")


Clev_map_plotly 

```




### Limitations: